apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone2-deployment
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: confuscious1/capstone1
        ports:
        - containerPort: 80
